defmodule TableParseTest do
  #import Issues.CLI, only: [parse_args: 1, sort_into_ascending_order: 1]
  import Issues.TableParser, only: [get_id_width: 1, get_created_at_width: 1, get_title_width: 1]
  use ExUnit.Case
  doctest Issues.TableParser

  test "Calculate id width returns correct value" do
    assert get_id_width([%{"id" => 100},%{"id" => 10000}]) == 5
  end

  test "Calculate created_at width returns correct value" do
    assert get_created_at_width([%{"created_at" => "2016-05-13T06:51:53Z"},%{"created_at" => "2017-04-27T14:46:02Z"}]) == 20
  end

  test "Calculate title width returns correct value" do
    assert get_title_width([%{"title" => "12345687"},%{"title" => "1234"}]) == 8
  end





  def fake_issues() do
    [
      %{
        "assignee" => nil, "assignees" => [],
        "body" => "Changes that can be done at any time:\r\n- [x] Support new Erlang typespec map syntax\r\n- [x] No longer include `__info__(:compile)[:time]` in `IEx.Helpers.i/1` info (this attribute has been removed)\r\n\r\nChanges that require exclusive Erlang 19 support (therefore we must wait until we drop Erlang 18):\r\n- [ ] Use `maps:take/2` and `maps:get/3`\r\n- [ ] Use `io_lib:scan_format/1` in Logger\r\n- [ ] Deprecate `%{foo => bar}` in typespecs without optional/required tagging\r\n-     [ ] Use `:trim_all` with `:binary.split/3` whenever parts is `:infinity` and `pattern != \"\"` in `String.split` and `String.Break.split`\r\n- [ ] Since bitstring comprehensions have been generalized to allow arbitrary expressions in the construction part, see if we can optimize the output generated by the compiler\r\n- [ ] Add `Port.monitor` and `Port.demonitor`\r\n- [ ] Remove all `otp_release` checks from the codebase\r\n",
        "closed_at" => nil, "comments" => 25,
        "comments_url" => "https://api.github.com/repos/elixir-lang/elixir/issues/4617/comments",
        "created_at" => "2016-05-13T06:51:53Z",
        "events_url" => "https://api.github.com/repos/elixir-lang/elixir/issues/4617/events",
        "html_url" => "https://github.com/elixir-lang/elixir/issues/4617",
        "id" => 154645367,
        "labels" => [%{"color" => "CCCCCC", "default" => false, "id" => 17739153,
           "name" => "App:Elixir",
           "url" => "https://api.github.com/repos/elixir-lang/elixir/labels/App:Elixir"},
         %{"color" => "009800", "default" => false, "id" => 4930795,
           "name" => "Kind:Enhancement",
           "url" => "https://api.github.com/repos/elixir-lang/elixir/labels/Kind:Enhancement"}],
        "labels_url" => "https://api.github.com/repos/elixir-lang/elixir/issues/4617/labels{/name}",
        "locked" => false, "milestone" => nil, "number" => 4617,
        "repository_url" => "https://api.github.com/repos/elixir-lang/elixir",
        "state" => "open", "title" => "Support Erlang 19 new features",
        "updated_at" => "2017-04-27T14:46:02Z",
        "url" => "https://api.github.com/repos/elixir-lang/elixir/issues/4617",
        "user" => %{"avatar_url" => "https://avatars3.githubusercontent.com/u/9582?v=3",
          "events_url" => "https://api.github.com/users/josevalim/events{/privacy}",
          "followers_url" => "https://api.github.com/users/josevalim/followers",
          "following_url" => "https://api.github.com/users/josevalim/following{/other_user}",
          "gists_url" => "https://api.github.com/users/josevalim/gists{/gist_id}",
          "gravatar_id" => "", "html_url" => "https://github.com/josevalim",
          "id" => 9582, "login" => "josevalim",
          "organizations_url" => "https://api.github.com/users/josevalim/orgs",
          "received_events_url" => "https://api.github.com/users/josevalim/received_events",
          "repos_url" => "https://api.github.com/users/josevalim/repos",
          "site_admin" => false,
          "starred_url" => "https://api.github.com/users/josevalim/starred{/owner}{/repo}",
          "subscriptions_url" => "https://api.github.com/users/josevalim/subscriptions",
          "type" => "User", "url" => "https://api.github.com/users/josevalim"}
      },
      %{
        "assignee" => nil, "assignees" => [],
        "body" => "Changes that can be done at any time:\r\n- [x] Support new Erlang typespec map syntax\r\n- [x] No longer include `__info__(:compile)[:time]` in `IEx.Helpers.i/1` info (this attribute has been removed)\r\n\r\nChanges that require exclusive Erlang 19 support (therefore we must wait until we drop Erlang 18):\r\n- [ ] Use `maps:take/2` and `maps:get/3`\r\n- [ ] Use `io_lib:scan_format/1` in Logger\r\n- [ ] Deprecate `%{foo => bar}` in typespecs without optional/required   tagging\r\n-   [ ] Use `:trim_all` with `:binary.split/3` whenever parts is `:infinity` and `pattern != \"\"` in `String.split` and `String.Break.split`\r\n- [ ] Since bitstring comprehensions have been generalized to allow arbitrary expressions in the construction part, see if we can optimize the output generated by the compiler\r\n- [ ] Add `Port.monitor` and `Port.demonitor`\r\n- [ ] Remove all `otp_release` checks from the codebase\r\n",
        "closed_at" => nil, "comments" => 25,
        "comments_url" => "https://api.github.com/repos/elixir-lang/elixir/issues/4617/comments",
        "created_at" => "2016-05-13T06:51:53Z",
        "events_url" => "https://api.github.com/repos/elixir-lang/elixir/issues/4617/events",
        "html_url" => "https://github.com/elixir-lang/elixir/issues/4617",
        "id" => 154645367,
        "labels" => [%{"color" => "CCCCCC", "default" => false, "id" => 17739153,
           "name" => "App:Elixir",
           "url" => "https://api.github.com/repos/elixir-lang/elixir/labels/App:Elixir"},
         %{"color" => "009800", "default" => false, "id" => 4930795,
           "name" => "Kind:Enhancement",
           "url" => "https://api.github.com/repos/elixir-lang/elixir/labels/Kind:Enhancement"}],
        "labels_url" => "https://api.github.com/repos/elixir-lang/elixir/issues/4617/labels{/name}",
        "locked" => false, "milestone" => nil, "number" => 4617,
        "repository_url" => "https://api.github.com/repos/elixir-lang/elixir",
        "state" => "open", "title" => "Support Erlang 19 new features",
        "updated_at" => "2017-04-27T14:46:02Z",
        "url" => "https://api.github.com/repos/elixir-lang/elixir/issues/4617",
        "user" => %{"avatar_url" => "https://avatars3.githubusercontent.com/u/9582?v=3",
          "events_url" => "https://api.github.com/users/josevalim/events{/privacy}",
          "followers_url" => "https://api.github.com/users/josevalim/followers",
          "following_url" => "https://api.github.com/users/josevalim/following{/other_user}",
          "gists_url" => "https://api.github.com/users/josevalim/gists{/gist_id}",
          "gravatar_id" => "", "html_url" => "https://github.com/josevalim",
          "id" => 9582, "login" => "josevalim",
          "organizations_url" => "https://api.github.com/users/josevalim/orgs",
          "received_events_url" => "https://api.github.com/users/josevalim/received_events",
          "repos_url" => "https://api.github.com/users/josevalim/repos",
          "site_admin" => false,
          "starred_url" => "https://api.github.com/users/josevalim/starred{/owner}{/repo}",
          "subscriptions_url" => "https://api.github.com/users/josevalim/subscriptions",
          "type" => "User", "url" => "https://api.github.com/users/josevalim"}
      }]
  end
end
